### ISSUE TITLE
Support for ADF 2.0?

### ISSUE THREAD

**Issue by jgoldhammer** [keensoft/ng2-alfresco-aos-editonline#1]
When trying to integrate it into the alfresco content app https://github.com/Alfresco/alfresco-content-app, the content-app is not build and run anymore...

Steps to reproduce:
1. Download the alfresco content-app via git clone
2. Build the content-app with npm install
3. Check that the content-app is running with npm start
4. Install your module with `npm install ng2-alfresco-aos-editonline --save``
5. Edit the app.module.ts of the content-app and insert the imports:
```
import { Ng2AlfrescoAosEditonlineModule, AOSEditOnlineService } from 'ng2-alfresco-aos-editonline';

...

@NgModule({
    imports: [
        BrowserModule,
        RouterModule.forRoot(APP_ROUTES, {
            useHash: true,
            enableTracing: false // enable for debug only
        }),
        AdfModule,
        CommonModule,
        MaterialModule,
        Ng2AlfrescoAosEditonlineModule.forRoot()

    ],
...
```

5. See log errors:
```
WARNING in ./node_modules/ng2-alfresco-datatable/node_modules/@angular/core/@angular/core.es5.js
5720:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/Users/jgoldhammer/development/sources/alfresco_adf/alfresco-content-app/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/jgoldhammer/development/sources/alfresco_adf/alfresco-content-app/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/Users/jgoldhammer/development/sources/alfresco_adf/alfresco-content-app/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/Users/jgoldhammer/development/sources/alfresco_adf/alfresco-content-app/node_modules/webpack/lib/Compiler.js:506:17)
    at /Users/jgoldhammer/development/sources/alfresco_adf/alfresco-content-app/node_modules/tapable/lib/Tapable.js:289:11
    at /Users/jgoldhammer/development/sources/alfresco_adf/alfresco-content-app/node_modules/html-webpack-plugin/index.js:60:9
    at tryCatcher (/Users/jgoldhammer/development/sources/alfresco_adf/alfresco-content-app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jgoldhammer/development/sources/alfresco_adf/alfresco-content-app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jgoldhammer/development/sources/alfresco_adf/alfresco-content-app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jgoldhammer/development/sources/alfresco_adf/alfresco-content-app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jgoldhammer/development/sources/alfresco_adf/alfresco-content-app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/jgoldhammer/development/sources/alfresco_adf/alfresco-content-app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/jgoldhammer/development/sources/alfresco_adf/alfresco-content-app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jgoldhammer/development/sources/alfresco_adf/alfresco-content-app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
 @ ./node_modules/ng2-alfresco-datatable/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ng2-alfresco-datatable/bundles/ng2-alfresco-datatable.js
 @ ./node_modules/ng2-alfresco-documentlist/bundles/ng2-alfresco-documentlist.js
 @ ./node_modules/ng2-alfresco-aos-editonline/bundles/ng2-alfresco-aos-editonline.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

The app does not load anymore...

**Comment by angelborroy-ks** [comment]
Thanks for your input, @jgoldhammer.

Currently AOS component is based in 1.X ADF. We'll try to make it compatible with 2.0 in the future.

**Comment by mikelasla** [comment]
You can check this new module for ADF 2.0.0 + AOS

https://www.npmjs.com/package/adf-aos-editonline-action

ADF guys didn't publish the 2.0.0 version for the ng2-alfresco-component yeoman generator that the old module was based on, so I end up creating a new one using their same approach (ng-packagr)

My plan is to get some time to deprecate the old one, but is hard to make this new one backwards compatible... maybe some more ng-packagr configuration

You can also check the result of our entire hackathon project [here](https://github.com/keensoft/alfresco-content-app-with-aos), which is a ready to test docker project with alfresco-content-app using our module

Regards

**Comment by jgoldhammer** [comment]
Thanks!
